# Generated by Django 5.2.1 on 2025-05-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
